parameters:
  - name: keepLastXDays
    displayName: Keep Last X Days
    type: number
    default: 30
  - name: dryRun
    displayName: Dry Run (don't delete)
    type: boolean
    default: false

pr: none
trigger: none

# run on weekly schedule
schedules:
  - cron: '0 7 * * 1'
    displayName: Monday 07:00 Purge
    branches:
      include:
        - main

pool: pins-odt-agent-pool

variables:
  - group: pipeline_secrets

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.21.1

jobs:
  - job: purge
    displayName: Cleanup Container Registry Images
    steps:
      - checkout: self
      - checkout: templates
      - template: steps/azure_auth.yml@templates
        parameters:
          subscriptionId: edb1ff78-90da-4901-a497-7e79f966f8e2
      - template: steps/azure_container_registry_purge.yml@templates
        parameters:
          dryRun: ${{ parameters.dryRun }}
          keepLastXDays: ${{ parameters.keepLastXDays }}
          repositories: "['service-name/image-1', 'service-name/image-2']"
          resourceGroupsBySub: >
            {
              "dev": ["pins-rg-service-name-dev"],
              "test": ["pins-rg-service-name-test"],
              "training": ["pins-rg-service-name-training"],
              "prod": ["pins-rg-service-name-prod"]
            }
    workspace:
      clean: all
