parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Dev
    values:
      - Dev
      - Test
      - Training
      - Prod

pool: pins-odt-agent-pool

pr: none
trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2

variables:
  - template: variables/environments/${{ lower(parameters.environment )}}.yml@templates
  - group: pipeline_secrets

jobs:
  - deployment: Seed_DB
    displayName: Seed ${{ parameters.environment }} SQL Database
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - checkout: self
            - task: Cache@2
              inputs:
                key: 'npm | "$(Agent.OS)" | package-lock.json'
                restoreKeys: |
                  npm | "$(Agent.OS)" | package-lock.json
                path: $(npm_config_cache)
              displayName: Cache NPM
            - template: steps/node_script.yml@templates
              parameters:
                nodeVersion: 22
                script: npm ci --workspace=@pins/service-name-database
                environmentVariables:
                  npm_config_cache: $(npm_config_cache)
            - template: steps/azure_auth.yml@templates
            - template: steps/azure_get_secrets.yml@templates
              parameters:
                keyVaultName: pins-kv-service-name-$(ENVIRONMENT)
                secrets:
                  - name: service-name-sql-app-connection-string
                    variable: SQL_CONNECTION_STRING
            - template: steps/node_script.yml@templates
              parameters:
                nodeVersion: 22
                condition: in('${{ parameters.environment }}', 'Dev', 'Test', 'Training')
                environmentVariables:
                  SQL_CONNECTION_STRING: $(SQL_CONNECTION_STRING)
                script: npm run generate && npm run seed
                workingDirectory: $(Build.Repository.LocalPath)/packages/database
            - template: steps/node_script.yml@templates
              parameters:
                condition: in('${{ parameters.environment }}', 'Prod')
                nodeVersion: 22
                environmentVariables:
                  SQL_CONNECTION_STRING: $(SQL_CONNECTION_STRING)
                script: npm run seed-prod
                workingDirectory: $(Build.Repository.LocalPath)/packages/database
    workspace:
      clean: all
