parameters:
  - name: schemaMigration
    displayName: Run SQL Database Migration
    type: boolean
    default: true
  - name: deployPortal
    displayName: Deploy the Portal
    type: boolean
    default: true
  - name: deployManage
    displayName: Deploy the Manage
    type: boolean
    default: true

pr: none
trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2
  pipelines:
    - pipeline: build
      source: Build
      trigger:
        branches:
          include:
            - main

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    variableGroupPrefix: 'cd'
    environments:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Training
        dependsOn:
          - Test
      - name: Prod
        dependsOn:
          - Training
    globalVariables:
      - template: .azure/pipelines/variables.yml@self
    deploymentStages:
      - name: Stage
        deploymentJobs:
          - name: Stage Portal
            condition: ${{ eq(parameters.deployPortal, true) }}
            steps:
              - template: ../steps/azure_web_app_deploy_slot.yml@templates
                parameters:
                  appName: pins-app-service-name-portal-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  azurecrName: $(azurecrName)
                  repository: service-name/portal
              - template: ../steps/azure_web_app_verify_git_hash.yml
                parameters:
                  appName: Portal
                  appUrl: $(deploySlotOutputs.slotUrl)/health
                  buildCommit: $(resources.pipeline.build.sourceCommit)
                  auth_enabled: 'false'
                  env: $(ENVIRONMENT)
          - name: Stage Manage
            condition: ${{ eq(parameters.deployManage, true) }}
            steps:
              - template: ../steps/azure_web_app_deploy_slot.yml@templates
                parameters:
                  appName: pins-app-service-name-manage-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  azurecrName: $(azurecrName)
                  repository: service-name/manage
              - template: ../steps/azure_web_app_verify_git_hash.yml
                parameters:
                  appName: Manage
                  appUrl: $(deploySlotOutputs.slotUrl)/health
                  buildCommit: $(resources.pipeline.build.sourceCommit)
                  auth_enabled: 'false'
                  env: $(ENVIRONMENT)
      - name: Deploy
        dependsOn:
          - Stage
        deploymentJobs:
          - name: Migrate
            condition: ${{ eq(parameters.schemaMigration, true) }}
            steps:
              - checkout: self
              - template: ../steps/azure_get_secrets.yml@templates
                parameters:
                  keyVaultName: pins-kv-service-name-$(ENVIRONMENT)
                  secrets:
                    - name: service-name-sql-admin-connection-string
                      variable: SQL_CONNECTION_STRING_ADMIN
                    - name: service-name-sql-app-connection-string
                      variable: SQL_CONNECTION_STRING
              - template: ../steps/node_script.yml@templates
                parameters:
                  nodeVersion: 22
                  script: npm ci --workspace=@pins/service-name-database
                  workingDirectory: $(Build.Repository.LocalPath)
              - ${{ if eq(parameters.schemaMigration, true) }}:
                  - template: ../steps/node_script.yml@templates
                    parameters:
                      nodeVersion: 22
                      environmentVariables:
                        SQL_CONNECTION_STRING_ADMIN: $(SQL_CONNECTION_STRING_ADMIN)
                      script: npm run migrate-prod
                      workingDirectory: $(Build.Repository.LocalPath)/packages/database
          - name: Deploy Portal
            condition: ${{ eq(parameters.deployPortal, true) }}
            steps:
              - template: ../steps/azure_web_app_slot_swap.yml
                parameters:
                  appName: pins-app-service-name-portal-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  appStagingSlotName: staging
                  appTargetSlotName: production
              - template: ../steps/azure_web_app_verify_git_hash.yml
                parameters:
                  appName: Manage
                  appUrl: https://pins-app-service-name-portal-$(ENVIRONMENT).azurewebsites.net/health
                  buildCommit: $(resources.pipeline.build.sourceCommit)
                  auth_enabled: 'false'
                  env: $(ENVIRONMENT)
          - name: Deploy Manage
            condition: ${{ eq(parameters.deployManage, true) }}
            steps:
              - template: ../steps/azure_web_app_slot_swap.yml
                parameters:
                  appName: pins-app-service-name-manage-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  appStagingSlotName: staging
                  appTargetSlotName: production
              - template: ../steps/azure_web_app_verify_git_hash.yml
                parameters:
                  appName: Manage
                  appUrl: https://pins-app-service-name-manage-$(ENVIRONMENT).azurewebsites.net/health
                  buildCommit: $(resources.pipeline.build.sourceCommit)
                  auth_enabled: 'false'
                  env: $(ENVIRONMENT)
          - name: Deploy Integration Functions
            steps:
              - download: build
                artifact: integration-functions
                displayName: Download integration-functions
              - template: ../steps/function_app_deploy.yml
                parameters:
                  appName: pins-func-service-name-integration-$(ENVIRONMENT)
                  resourceGroup: $(resourceGroup)
                  workingDirectory: $(Pipeline.Workspace)/build/integration-functions
