trigger:
  branches:
    include:
      - main # run on main before build
      # trigger for merge queue branches
      - gh-readonly-queue/*

pr:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - infrastructure

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    gitFetchDepth: 0
    skipAzureAuth: true
    validationJobs:
      - name: Run Linting & Tests
        steps:
          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)" | package-lock.json
              path: $(npm_config_cache)
            displayName: Cache NPM
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm ci
              environmentVariables:
                npm_config_cache: $(npm_config_cache)
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              # ensure @pins/service-name-database/src/client is generated for tests that use it
              # this will also catch schema validation errors
              script: npm run db-generate
          - template: ../steps/node_script.yml
            parameters:
              # only run commitlint on branches, not main
              condition: ne(variables['Build.SourceBranchName'], 'main')
              nodeVersion: 22
              script: npm run commitlint
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm run check-types
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm run lint
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm run format-check
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm run test-coverage
          # run build for any web apps
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              workingDirectory: $(Build.Repository.LocalPath)/apps/portal
              script: npm run build
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              workingDirectory: $(Build.Repository.LocalPath)/apps/manage
              script: npm run build
